---
title: "Growth-coupled sensitivity of the *lac* operon in *E. coli*"
author: Thomas Julou
output:
  html_document:
    toc: false
    toc_float: false
---

<!-- <iframe width="853" height="480" src="https://www.youtube.com/embed/2Tznm868fmc?rel=0" frameborder="0" allowfullscreen></iframe> -->


# Dataset description

```{r}
(mytables[['lacl_list']] <- 
   myframes %>% ungroup() %>% 
   filter(!discard_top, !discard_start) %>% 
   filter(str_detect(condition, "switch")) %>% 
   filter(!str_detect(condition, "stdIllum")) %>% 
   mutate(label=rename_conds(condition)) %>% 
   # start from the total number of observations
   group_by(condition, label, date, pos, gl) %>%
   summarise(n_obs=n()) %>%
   # add the number of dividing cells
   left_join(myframes %>%
               ungroup() %>% 
               filter(!discard_top, end_type=='div') %>% 
               group_by(date, pos, gl, id) %>% 
               filter(!any(discard_start)) %>% 
               slice(1) %>% 
               group_by(date, pos, gl) %>% 
               summarise(n_div_cells=n()) ) %>%
   # add the number of frames
   left_join(myframes %>%
               group_by(date, pos, gl) %>% 
               summarise(nframes=max(frame)+1) ) %>% 
   # mutate(condition=factor(condition, levels=unique(condition_ts$condition)) ) %>% 
   group_by(condition, label, date) %>%
   summarise(n_lanes=length(unique(interaction(date, pos, gl))),
             # n_div_cells=sum(is.na(n_div_cells)),
             n_div_cells=sum(n_div_cells),
             n_obs=sum(n_obs) ) %>% 
   left_join(
     mycells_switching %>% 
       ungroup %>% 
       filter(! date %in% discarded_dates) %>% 
       group_by(condition, date) %>%
       summarise(
         n_switch=n(),
         n_lags=sum(!is.na(lag_1000)),
         n_discard=sum(logl_time_slope_before <= min_growth_rate, na.rm=TRUE) ) %>% 
       mutate(n_discard=ifelse(condition=='switch_gly_lac', NA, n_discard) )
   )
) %>% 
  filter(! date %in% discarded_dates) %>% 
  knitr::kable()

```

```{r}
(mytables[['sugarmix_list']] <- 
    myrates_mix %>% 
    bind_rows(
       myrates_mix_all %>% 
          filter( (condition=="lac002_glu32uM" & date != 20210504) 
                  | (date==20210122 & condition=="lac002_glu16uM") ) %>% 
          filter(n>10) %>% 
          filter(induced<.05 | induced>.95) %>% 
          mutate(induced=round(induced))
    ) %>% 
    # start from the total number of observations
    group_by(condition, date) %>%
    summarise(n_cells=n(), p_induced=signif(sum(induced)/n_cells, 2)) %>%
    # add the number of gls
    left_join(myframes %>%
                 ungroup() %>% 
                 filter(!discard_top) %>% 
                 group_by(condition, date, pos, gl) %>% 
                 slice(1) %>% 
                 group_by(condition, date) %>% 
                 summarise(n_gls=n())
    ) %>% 
    # add the number of frames
    left_join(myframes %>%
                 group_by(condition, date) %>% 
                 summarise(nframes=max(frame)+1) ) %>% 
    ungroup() %>% 
    parse_sugarmix_conds(condition) %>% 
    select(-condition) %>%
    arrange(treatment, glu) %>% relocate(treatment) %>% 
    mutate(glu=signif(glu * 200/1110, 2)) %>% 
    #add M9 zero control
    bind_rows(
       myframes %>% 
          filter(condition=="M9zero") %>% 
          # remove frames after touching the exit
          group_by(id, .add=TRUE) %>%
          mutate(discard_top=which_touch_exit(vertical_top, 1)) %>%
          mutate(discard_top=ifelse(discard_start, FALSE, discard_top)) %>% # not in the preexpt step (2h)
          mutate(end_type=ifelse(any(discard_top), 'touchtop', end_type)) %>% # update end_type to exit for cells which have touched the vertical cutoff
          # remove daughters of cells that touched the exit
          group_by(path) %>%
          mutate(discard_top=which_to_progeny(discard_top, cid)) %>%
          filter(!discard_top) %>% 
          group_by(date, pos, gl, id) %>% 
          filter(n() > 5) %>% # fit on 5 points per time window so 5 points at least 
          filter(frame==max(frame)) %>% 
          group_by(date) %>% 
          summarise(treatment="M9 zero", glu=0, n_cells=n(), p_induced=0, 
                    n_gls=length(unique(interaction(pos, gl))), nframes=max(frame)+1)
    )
) %>% 
   print(n=Inf)


```


## Colophon

```{r}
devtools::loaded_packages() %>% 
  mutate(version = unlist(lapply(package, function(x) as.character(packageVersion(x)))) ) %>% 
  arrange(package) %>% 
  select(-path) %>% 
  knitr::kable(row.names=FALSE)

```


